version: '3.8'

services:
  fomodog:
    image: smixers/fomodog:latest 
    container_name: fomodog
    mem_limit: 128M
    mem_reservation: 128M
    build:
      context: .
      dockerfile: Dockerfile