version: '3.8'

services:
  fomodog:
    image: ${DOCKER_REGISTRY-}fomodog 
    labels:
      com.microsoft.visual-studio.project-name: "FomoDog"
    container_name: fomodog
    mem_limit: 128M
    mem_reservation: 128M
    build:
      context: .
      dockerfile: Dockerfile
    environment:  # Add environment variables required for your application to connect to the DB
      - DATABASE_URL=postgres://postgres:password@db:5432/fomodog
    depends_on:
      - db  # This ensures fomodog starts only after the db service is up

  db:
    image: postgres:16.0
    container_name: fomodog_postgres
    environment:
      POSTGRES_DB: fomodog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: