name: FomoDog-service

on:
  push:
    branches:
      - master
    paths:
      - 'src/FomoDog/**'
      - 'src/FomoDog.MessageTypes/**'

jobs:
  checkout-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Build and Push Docker image
        uses: BooAIPublic/github-workflows/.github/workflows/build-and-push.yml@master
        with:
          image: "smixers/fomodog"
          dockerfile: ./src/FomoDog/Dockerfile
          context: ./src/
          tests: true
        secrets:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

  extract-coverage:
    runs-on: ubuntu-latest
    needs: checkout-and-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract coverage reports
        run: |
          docker create --name temp-container smixers/fomodog:latest
          docker cp temp-container:/app/coverage/ coverage/
          docker rm temp-container

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./coverage/
          flags: FomoDog-service
